CC=gcc
LDLIBS=-lcs50
CFLAGS=-o

plurality: plurality.c
	$(CC) $(CFLAGS) plurality plurality.c $(LDLIBS)

runoff: runoff.c
	$(CC) $(CFLAGS) runoff runoff.c $(LDLIBS)

tideman: tideman.c
	$(CC) $(CFLAGS) tideman tideman.c $(LDLIBS)