cc=gcc
LDLIBS=-lcs50
CFLAGS=-o

population: population.c
	$(CC) $(CFLAGS) population population.c $(LDLIBS)

scarbble: scarbble.c
	$(CC) $(CFLAGS) scarbble scarbble.c $(LDLIBS)

sort: ./sort/sort.c
	$(CC) $(CFLAGS) sort ./sort/sort.c $(LDLIBS)
